#!/usr/bin/env bash
# Generated by samsara-cli — do not edit manually.
# Hook: session-start
# Event: session_start
set -euo pipefail

SKILLS_DIR=".gemini/skills"
BOOTSTRAP_PATH="${SKILLS_DIR}/samsara-samsara-bootstrap/SKILL.md"

# Consume stdin so Gemini's hook protocol can pass JSON without blocking.
cat >/dev/null || true

escape_for_json() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    s="${s//$'\n'/\\n}"
    s="${s//$'\r'/\\r}"
    s="${s//$'\t'/\\t}"
    printf '%s' "$s"
}

if [ -f "${BOOTSTRAP_PATH}" ]; then
    bootstrap_content=$(cat "${BOOTSTRAP_PATH}")
    degraded="false"
else
    bootstrap_content="DEGRADED: Samsara bootstrap skill not found at ${BOOTSTRAP_PATH}."
    degraded="true"
fi

bootstrap_escaped=$(escape_for_json "$bootstrap_content")
session_context="<IMPORTANT>\nYou are operating under the Samsara framework (向死而驗).\n\n**Below is the full content of your 'samsara:samsara-bootstrap' skill:**\n\n${bootstrap_escaped}\n</IMPORTANT>"

if [ "${degraded}" = "true" ]; then
    session_context="<IMPORTANT>\nSamsara bootstrap context loading is degraded.\n\n${bootstrap_escaped}\n</IMPORTANT>"
fi

session_context_escaped=$(escape_for_json "$session_context")
printf '{"hookSpecificOutput":{"additionalContext":"%s"}}\n' "$session_context_escaped"
