#!/usr/bin/env bash
# Generated by samsara-cli — do not edit manually.
# Hook: session-start
# Event: session_start
set -euo pipefail

# Session start hook for Samsara on Codex.
# Returns model-visible SessionStart additional context.

# Resolve the install root from this script's location:
#   <install-root>/.codex/hooks/samsara-session-start.sh
# This keeps project and global installs independent from the process cwd.
HOOK_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_ROOT="$(cd "${HOOK_SCRIPT_DIR}/../.." && pwd)"
CONFIGURED_SKILLS_DIR=".agents/skills"
if [[ "${CONFIGURED_SKILLS_DIR}" = /* ]]; then
  SKILLS_DIR="${CONFIGURED_SKILLS_DIR}"
else
  SKILLS_DIR="${INSTALL_ROOT}/${CONFIGURED_SKILLS_DIR}"
fi

# Read samsara-bootstrap content for context injection
bootstrap_content=$(cat "${SKILLS_DIR}/samsara-samsara-bootstrap/SKILL.md" 2>&1 || echo "Error reading samsara-bootstrap skill")

# Escape string for JSON embedding.
# Handles: backslash, double-quote, newline, carriage-return, tab.
# Known gap: Unicode control characters (U+0000-U+001F) are not escaped.
# If SKILL.md contains raw control characters, JSON output will be malformed.
# This is a known limitation documented in the scar report.
escape_for_json() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    s="${s//$'\n'/\\n}"
    s="${s//$'\r'/\\r}"
    s="${s//$'\t'/\\t}"
    printf '%s' "$s"
}

bootstrap_escaped=$(escape_for_json "$bootstrap_content")
session_context="<IMPORTANT>\nYou are operating under the Samsara framework (向死而驗).\n\n**Below is the full content of your 'samsara-bootstrap' skill:**\n\n${bootstrap_escaped}\n</IMPORTANT>"

# Codex exposes systemMessage to the UI/event stream. Model context belongs in
# hookSpecificOutput.additionalContext for SessionStart.
printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' "$session_context"

exit 0
